version: '3.8'

services:
  bd:
    image: postgres
    container_name: postgres-db
    ports:
      - '8080:8080'
    volumes:
      - digital-book-store:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DigitalBookStore

volumes:
  postgres_data: